//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tag: Option<String>,
    pub file_extension: String,
    pub file_key: String,
    #[sea_orm(column_type = "Float")]
    pub top: f32,
    #[sea_orm(column_type = "Float")]
    pub left: f32,
    #[sea_orm(column_type = "Float")]
    pub width: f32,
    #[sea_orm(column_type = "Float")]
    pub height: f32,
    pub ori_width: u32,
    pub ori_height: u32,
    pub valid: i8,
    pub attach_id: i32,
    pub page: u32,
    pub source_type: String,
    pub desp: Option<String>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
