//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::attachments::Entity as Attachments;
pub use super::audios::Entity as Audios;
pub use super::chat_records::Entity as ChatRecords;
pub use super::gamecases::Entity as Gamecases;
pub use super::images::Entity as Images;
pub use super::videos::Entity as Videos;
